version: "3.9"

services:
  # ================= USER SERVICE =================
  user-service:
    build: ./user-service
    ports:
      - "8001:3000"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      DB_HOST: user-db
      DB_USER: user
      DB_PASS: password
      DB_NAME: userdb

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - userdb:/var/lib/postgresql/data
      - ./user-service/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-db-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - user-db

  # ================= PRODUCT SERVICE =================
  product-service:
    build: ./product-service
    ports:
      - "8002:3000"
    environment:
      DB_HOST: product-db
      DB_USER: root
      DB_PASS: root
      DB_NAME: productdb
    depends_on:
      - product-db

  product-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - productdb:/var/lib/mysql
      - ./product-service/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  product-db-admin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: product-db
    depends_on:
      - product-db

  # ================= CART SERVICE =================
  cart-service:
    build: ./cart-service
    ports:
      - "8003:8000"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:3000
      USER_SERVICE_URL: http://user-service:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
      product-service:
        condition: service_started

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ================= REVIEW SERVICE =================
  review-service:
    build: ./review-service
    ports:
      - "8004:8004"
    environment:
      MONGO_HOST: review-db
      MONGO_PORT: 27017
      MONGO_DB: reviewdb
    depends_on:
      review-db:
        condition: service_healthy

  review-db:
    image: mongo:7
    container_name: ecommerce-microservices-review-db-1
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: reviewdb
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  userdb:
  productdb:
  cartdb:
  reviewdb:
