version: "3.9"

services:

# USER-SERVICE
  user-service:
    build: ./user-service
    ports:
      - "8001:3000"
    environment:
      DB_HOST: user-db
      DB_NAME: userdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - user-db

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  user-db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

# PRODUCT-SERVICE
  product-service:
    build: ./product-service
    ports:
      - "8002:3000"
    environment:
      DB_HOST: product-db
      DB_NAME: productdb
      DB_USER: root
      DB_PASS: root
    depends_on:
      - product-db

  product-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  product-db-admin:
    image: phpmyadmin
    environment:
      PMA_HOST: product-db
    ports:
      - "8081:80"
